from pathlib import Path
import shutil
import sys

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()

def replace(path, old, new, count=-1):
    p = root / path
    text = p.read_text()
    if old not in text:
        raise RuntimeError(f"Expected modernization anchor missing in {path}: {old[:80]!r}")
    p.write_text(text.replace(old, new, count))

# Version
replace("gradle.properties", "mod_version=0.5.9-alpha", "mod_version=0.6.0-alpha")

# Shared machine redstone + IO modes.
util = root / "src/main/java/com/loyacrown/enderlegacy/util"
util.mkdir(parents=True, exist_ok=True)
(util / "MachineRedstoneMode.java").write_text('''package com.loyacrown.enderlegacy.util;\n\npublic enum MachineRedstoneMode {\n    ALWAYS_ACTIVE("Always On"),\n    ACTIVE_WITH_SIGNAL("With Signal"),\n    ACTIVE_WITHOUT_SIGNAL("Without Signal"),\n    NEVER_ACTIVE("Never");\n\n    private final String displayName;\n    MachineRedstoneMode(String displayName) { this.displayName = displayName; }\n    public String displayName() { return displayName; }\n    public MachineRedstoneMode next() {\n        MachineRedstoneMode[] values = values();\n        return values[(ordinal() + 1) % values.length];\n    }\n}\n''')
(util / "MachineIOMode.java").write_text('''package com.loyacrown.enderlegacy.util;\n\npublic enum MachineIOMode {\n    DISABLED("Off"), INPUT("Input"), OUTPUT("Output"), INPUT_OUTPUT("In/Out");\n\n    private final String displayName;\n    MachineIOMode(String displayName) { this.displayName = displayName; }\n    public String displayName() { return displayName; }\n    public boolean allowsInput() { return this == INPUT || this == INPUT_OUTPUT; }\n    public boolean allowsOutput() { return this == OUTPUT || this == INPUT_OUTPUT; }\n    public MachineIOMode next() {\n        MachineIOMode[] values = values();\n        return values[(ordinal() + 1) % values.length];\n    }\n}\n''')

powered = "src/main/java/com/loyacrown/enderlegacy/blockentity/LegacyPoweredBlockEntity.java"
replace(powered, "import com.loyacrown.enderlegacy.util.MutableEnergyStorage;", "import com.loyacrown.enderlegacy.util.MutableEnergyStorage;\nimport com.loyacrown.enderlegacy.util.MachineRedstoneMode;")
replace(powered, "    private LazyOptional<IEnergyStorage> energyCapability = LazyOptional.empty();", "    private LazyOptional<IEnergyStorage> energyCapability = LazyOptional.empty();\n    private MachineRedstoneMode redstoneMode = MachineRedstoneMode.ALWAYS_ACTIVE;")
replace(powered, "    public MutableEnergyStorage energy() {\n        return energy;\n    }", '''    public MutableEnergyStorage energy() {\n        return energy;\n    }\n\n    public MachineRedstoneMode getRedstoneMode() { return redstoneMode; }\n\n    public void setRedstoneMode(MachineRedstoneMode mode) {\n        redstoneMode = mode == null ? MachineRedstoneMode.ALWAYS_ACTIVE : mode;\n        setChanged();\n    }\n\n    public void cycleRedstoneMode() { setRedstoneMode(redstoneMode.next()); }\n\n    protected boolean isMachineEnabledByRedstone() {\n        if (level == null) return false;\n        boolean powered = level.hasNeighborSignal(worldPosition);\n        return switch (redstoneMode) {\n            case ALWAYS_ACTIVE -> true;\n            case ACTIVE_WITH_SIGNAL -> powered;\n            case ACTIVE_WITHOUT_SIGNAL -> !powered;\n            case NEVER_ACTIVE -> false;\n        };\n    }''')
replace(powered, '        tag.putInt("Energy", energy.getEnergyStored());', '        tag.putInt("Energy", energy.getEnergyStored());\n        tag.putString("RedstoneMode", redstoneMode.name());')
replace(powered, '        energy.setEnergyStored(tag.getInt("Energy"));', '''        energy.setEnergyStored(tag.getInt("Energy"));\n        if (tag.contains("RedstoneMode")) {\n            try { redstoneMode = MachineRedstoneMode.valueOf(tag.getString("RedstoneMode")); }\n            catch (IllegalArgumentException ignored) { redstoneMode = MachineRedstoneMode.ALWAYS_ACTIVE; }\n        }''')

farm = "src/main/java/com/loyacrown/enderlegacy/blockentity/FarmingStationBlockEntity.java"
replace(farm, "import com.loyacrown.enderlegacy.util.MachineInteractionUtil;", "import com.loyacrown.enderlegacy.util.MachineInteractionUtil;\nimport com.loyacrown.enderlegacy.util.MachineIOMode;")
replace(farm, "import net.minecraftforge.items.ItemStackHandler;", "import net.minecraftforge.items.ItemStackHandler;\nimport net.minecraftforge.items.IItemHandler;")
replace(farm, "import java.util.HashSet;", "import java.util.HashSet;\nimport java.util.EnumMap;\nimport java.util.Map;")
replace(farm, "    private boolean supplySlotsLocked;", "    private boolean supplySlotsLocked;\n    private final Map<Direction, MachineIOMode> sideModes = new EnumMap<>(Direction.class);\n    private final Map<Direction, LazyOptional<IItemHandler>> sideCapabilities = new EnumMap<>(Direction.class);")
replace(farm, '''    public FarmingStationBlockEntity(BlockPos pos, BlockState state) {\n        super(LegacyBlockEntities.FARMING_STATION.get(), pos, state, 1_000_000, 4_000, 0);\n    }''', '''    public FarmingStationBlockEntity(BlockPos pos, BlockState state) {\n        super(LegacyBlockEntities.FARMING_STATION.get(), pos, state, 1_000_000, 4_000, 0);\n        for (Direction direction : Direction.values()) sideModes.put(direction, MachineIOMode.INPUT_OUTPUT);\n    }''')
replace(farm, "        itemCapability = LazyOptional.of(() -> inventory);", '''        itemCapability = LazyOptional.of(() -> inventory);\n        sideCapabilities.clear();\n        for (Direction direction : Direction.values()) {\n            sideCapabilities.put(direction, LazyOptional.of(() -> new FarmingSidedItemHandler(direction)));\n        }''')
replace(farm, "        itemCapability.invalidate();", '''        itemCapability.invalidate();\n        for (LazyOptional<IItemHandler> capability : sideCapabilities.values()) capability.invalidate();\n        sideCapabilities.clear();''')
replace(farm, '''        if (cap == ForgeCapabilities.ITEM_HANDLER) {\n            return itemCapability.cast();\n        }''', '''        if (cap == ForgeCapabilities.ITEM_HANDLER) {\n            if (side == null) return itemCapability.cast();\n            MachineIOMode mode = sideModes.getOrDefault(side, MachineIOMode.INPUT_OUTPUT);\n            if (mode == MachineIOMode.DISABLED) return LazyOptional.empty();\n            LazyOptional<IItemHandler> sided = sideCapabilities.get(side);\n            return sided == null ? LazyOptional.empty() : sided.cast();\n        }''')
replace(farm, '''        if (!(level instanceof ServerLevel serverLevel)) {\n            return;\n        }''', '''        if (!(level instanceof ServerLevel serverLevel)) {\n            return;\n        }\n        if (!isMachineEnabledByRedstone()) return;''', 1)
replace(farm, "    public boolean areSupplySlotsLocked() {", '''    public MachineIOMode getSideMode(Direction direction) {\n        return sideModes.getOrDefault(direction, MachineIOMode.INPUT_OUTPUT);\n    }\n\n    public void cycleSideMode(Direction direction) {\n        sideModes.put(direction, getSideMode(direction).next());\n        setChanged();\n    }\n\n    public int getSideModeOrdinal(Direction direction) { return getSideMode(direction).ordinal(); }\n\n    private final class FarmingSidedItemHandler implements IItemHandler {\n        private final Direction side;\n        private FarmingSidedItemHandler(Direction side) { this.side = side; }\n        @Override public int getSlots() { return inventory.getSlots(); }\n        @Override public ItemStack getStackInSlot(int slot) { return inventory.getStackInSlot(slot); }\n        @Override public ItemStack insertItem(int slot, ItemStack stack, boolean simulate) {\n            if (!getSideMode(side).allowsInput() || !isAutomationInputSlot(slot)) return stack;\n            return inventory.insertItem(slot, stack, simulate);\n        }\n        @Override public ItemStack extractItem(int slot, int amount, boolean simulate) {\n            if (!getSideMode(side).allowsOutput() || !isAutomationOutputSlot(slot)) return ItemStack.EMPTY;\n            return inventory.extractItem(slot, amount, simulate);\n        }\n        @Override public int getSlotLimit(int slot) { return inventory.getSlotLimit(slot); }\n        @Override public boolean isItemValid(int slot, ItemStack stack) {\n            return getSideMode(side).allowsInput() && isAutomationInputSlot(slot) && inventory.isItemValid(slot, stack);\n        }\n    }\n\n    private static boolean isAutomationInputSlot(int slot) {\n        return slot == HOE_SLOT || slot == AXE_SLOT || (slot >= FIRST_SUPPLY_SLOT && slot <= LAST_SUPPLY_SLOT) || slot == CAPACITOR_SLOT;\n    }\n    private static boolean isAutomationOutputSlot(int slot) { return slot >= FIRST_OUTPUT_SLOT && slot <= LAST_OUTPUT_SLOT; }\n\n    public boolean areSupplySlotsLocked() {''')
replace(farm, '''                    case 3 -> supplySlotsLocked ? 1 : 0;\n                    default -> 0;''', '''                    case 3 -> supplySlotsLocked ? 1 : 0;\n                    case 4 -> getRedstoneMode().ordinal();\n                    case 5 -> getSideModeOrdinal(Direction.DOWN);\n                    case 6 -> getSideModeOrdinal(Direction.UP);\n                    case 7 -> getSideModeOrdinal(Direction.NORTH);\n                    case 8 -> getSideModeOrdinal(Direction.SOUTH);\n                    case 9 -> getSideModeOrdinal(Direction.WEST);\n                    case 10 -> getSideModeOrdinal(Direction.EAST);\n                    default -> 0;''')
replace(farm, "                return 4;", "                return 11;", 1)
replace(farm, '        tag.put("SupplySlotLocks", locks);', '''        tag.put("SupplySlotLocks", locks);\n        CompoundTag sides = new CompoundTag();\n        for (Direction direction : Direction.values()) sides.putString(direction.getName(), getSideMode(direction).name());\n        tag.put("SideModes", sides);''')
replace(farm, '''        for (int i = 0; i < supplySlotLocks.length; i++) {\n            supplySlotLocks[i] = locks.getString("Slot" + i);\n        }\n    }''', '''        for (int i = 0; i < supplySlotLocks.length; i++) supplySlotLocks[i] = locks.getString("Slot" + i);\n        CompoundTag sides = tag.getCompound("SideModes");\n        for (Direction direction : Direction.values()) {\n            String saved = sides.getString(direction.getName());\n            if (!saved.isBlank()) {\n                try { sideModes.put(direction, MachineIOMode.valueOf(saved)); }\n                catch (IllegalArgumentException ignored) { sideModes.put(direction, MachineIOMode.INPUT_OUTPUT); }\n            }\n        }\n    }''')

menu = "src/main/java/com/loyacrown/enderlegacy/menu/FarmingStationMenu.java"
replace(menu, "import net.minecraft.core.BlockPos;", "import net.minecraft.core.BlockPos;\nimport net.minecraft.core.Direction;\nimport com.loyacrown.enderlegacy.util.MachineRedstoneMode;\nimport com.loyacrown.enderlegacy.util.MachineIOMode;")
replace(menu, "public class FarmingStationMenu extends AbstractContainerMenu {", '''public class FarmingStationMenu extends AbstractContainerMenu {\n    public static final int SUPPLY_LOCK_BUTTON_ID = 0;\n    public static final int FIRST_SIDE_BUTTON_ID = 1;\n    public static final int REDSTONE_BUTTON_ID = 7;''')
replace(menu, "new SimpleContainerData(4)", "new SimpleContainerData(11)")
replace(menu, '''    public boolean areSupplySlotsLocked() {\n        return data.get(3) != 0;\n    }''', '''    public boolean areSupplySlotsLocked() { return data.get(3) != 0; }\n\n    public MachineRedstoneMode getRedstoneMode() {\n        MachineRedstoneMode[] values = MachineRedstoneMode.values();\n        return values[Math.floorMod(data.get(4), values.length)];\n    }\n\n    public MachineIOMode getSideMode(Direction direction) {\n        MachineIOMode[] values = MachineIOMode.values();\n        return values[Math.floorMod(data.get(5 + direction.ordinal()), values.length)];\n    }''')
replace(menu, '''        if (id == 0) {\n            if (!player.level().isClientSide) {\n                station.toggleSupplySlotsLocked();\n            }\n            return true;\n        }\n        return super.clickMenuButton(player, id);''', '''        if (id == SUPPLY_LOCK_BUTTON_ID) {\n            if (!player.level().isClientSide) station.toggleSupplySlotsLocked();\n            return true;\n        }\n        if (id >= FIRST_SIDE_BUTTON_ID && id < FIRST_SIDE_BUTTON_ID + 6) {\n            if (!player.level().isClientSide) station.cycleSideMode(Direction.values()[id - FIRST_SIDE_BUTTON_ID]);\n            return true;\n        }\n        if (id == REDSTONE_BUTTON_ID) {\n            if (!player.level().isClientSide) station.cycleRedstoneMode();\n            return true;\n        }\n        return super.clickMenuButton(player, id);''')

screen = "src/main/java/com/loyacrown/enderlegacy/client/FarmingStationScreen.java"
replace(screen, "import net.minecraft.world.entity.player.Inventory;", "import net.minecraft.world.entity.player.Inventory;\nimport net.minecraft.core.Direction;\nimport java.util.EnumMap;\nimport java.util.Map;")
replace(screen, "    private Button supplyLockButton;", "    private Button supplyLockButton;\n    private Button redstoneButton;\n    private final Map<Direction, Button> sideButtons = new EnumMap<>(Direction.class);")
replace(screen, "        this.imageWidth = 184;", "        this.imageWidth = 270;")
replace(screen, '''                .bounds(leftPos + 126, topPos + 4, 50, 16)\n                .build());\n    }''', '''                .bounds(leftPos + 126, topPos + 4, 50, 16)\n                .build());\n        sideButtons.clear();\n        int y = topPos + 28;\n        for (Direction direction : Direction.values()) {\n            final Direction d = direction;\n            Button sideButton = addRenderableWidget(Button.builder(Component.literal(sideLabel(d)), button -> {\n                if (minecraft != null && minecraft.gameMode != null) minecraft.gameMode.handleInventoryButtonClick(menu.containerId, 1 + d.ordinal());\n            }).bounds(leftPos + 190, y, 72, 16).build());\n            sideButtons.put(d, sideButton);\n            y += 18;\n        }\n        redstoneButton = addRenderableWidget(Button.builder(Component.literal(redstoneLabel()), button -> {\n            if (minecraft != null && minecraft.gameMode != null) minecraft.gameMode.handleInventoryButtonClick(menu.containerId, FarmingStationMenu.REDSTONE_BUTTON_ID);\n        }).bounds(leftPos + 190, topPos + 138, 72, 16).build());\n    }\n\n    private String sideLabel(Direction direction) { return shortDirection(direction) + ": " + menu.getSideMode(direction).displayName(); }\n    private String redstoneLabel() { return "RS: " + menu.getRedstoneMode().displayName(); }\n    private static String shortDirection(Direction direction) {\n        return switch (direction) {\n            case DOWN -> "Down"; case UP -> "Up"; case NORTH -> "North";\n            case SOUTH -> "South"; case WEST -> "West"; case EAST -> "East";\n        };\n    }''')
replace(screen, "        graphics.blit(TEXTURE, leftPos, topPos, 0, 0, imageWidth, imageHeight);", '''        graphics.blit(TEXTURE, leftPos, topPos, 0, 0, 184, imageHeight);\n        graphics.fill(leftPos + 184, topPos, leftPos + imageWidth, topPos + imageHeight, 0xFFE8E8E8);\n        graphics.fill(leftPos + 185, topPos + 1, leftPos + imageWidth - 1, topPos + imageHeight - 1, 0xFFB8B8B8);''')
replace(screen, '        graphics.drawString(font, Component.literal("Range: " + menu.getFarmRange()), 98, 20, 0x404040, false);', '        graphics.drawString(font, Component.literal("Range: " + menu.getFarmRange()), 98, 20, 0x404040, false);\n        graphics.drawString(font, Component.literal("Side Configuration"), 190, 8, 0x303030, false);')
replace(screen, '''        if (supplyLockButton != null) {\n            supplyLockButton.setMessage(Component.translatable(menu.areSupplySlotsLocked()\n                    ? "gui.loyacrowns_ender_legacy.farming_station.unlock"\n                    : "gui.loyacrowns_ender_legacy.farming_station.lock"));\n        }''', '''        if (supplyLockButton != null) {\n            supplyLockButton.setMessage(Component.translatable(menu.areSupplySlotsLocked()\n                    ? "gui.loyacrowns_ender_legacy.farming_station.unlock"\n                    : "gui.loyacrowns_ender_legacy.farming_station.lock"));\n        }\n        for (var entry : sideButtons.entrySet()) entry.getValue().setMessage(Component.literal(sideLabel(entry.getKey())));\n        if (redstoneButton != null) redstoneButton.setMessage(Component.literal(redstoneLabel()));''')

# Modern texture aliases retain the proven legacy art while giving the 0.6.0 model stable modern names.
textures = root / "src/main/resources/assets/loyacrowns_ender_legacy/textures/block"
for source, target in [
    ("farm_side_1_12.png", "farming_station_side_modern.png"),
    ("soul_machine_top_1_12.png", "soul_machine_top_modern.png"),
    ("soul_machine_bottom_1_12.png", "soul_machine_bottom_modern.png"),
]:
    shutil.copyfile(textures / source, textures / target)
models = root / "src/main/resources/assets/loyacrowns_ender_legacy/models/block"
shutil.copyfile(models / "farming_station.json", models / "farming_station_legacy.json")
print("Applied 0.6.0 Farming Station modernization patch")
